-- MySQL Script generated by MySQL Workbench
-- Mon Nov 15 12:05:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema emergencies_cnt_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `emergencies_cnt_db` ;

-- -----------------------------------------------------
-- Schema emergencies_cnt_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `emergencies_cnt_db` ;
USE `emergencies_cnt_db` ;

-- -----------------------------------------------------
-- Table `emergencies_cnt_db`.`emergencyPatients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `emergencies_cnt_db`.`emergencyPatients` ;

CREATE TABLE IF NOT EXISTS `emergencies_cnt_db`.`emergencyPatients` (
  `idEmergencyPatients` INT NOT NULL AUTO_INCREMENT,
  `documentNumberEmergencyPatients` VARCHAR(15) NOT NULL,
  `namesEmergencyPatients` VARCHAR(30) NOT NULL,
  `lastNamesEmergencyPatients` VARCHAR(30) NOT NULL,
  `ageEmergencyPatients` INT NOT NULL,
  `addressEmergencyPatients` VARCHAR(40) NULL,
  `genderEmergencyPatients` VARCHAR(10) NULL,
  `weightEmergencyPatients` INT NOT NULL,
  `heightEmergencyPatients` INT NOT NULL,
  `smokerEmergencyPatients` INT NOT NULL DEFAULT 0,
  `dietEmergencyPatients` INT NOT NULL,
  `heightWeightRatioEmergencyPatients` DOUBLE NULL DEFAULT 0.0,
  `priorityEmergencyPatients` DOUBLE NULL,
  `riskEmergencyPatients` DOUBLE NULL,
  `statusEmergencyPatients` VARCHAR(30) NULL DEFAULT 'PENDING',
  PRIMARY KEY (`idEmergencyPatients`),
  UNIQUE INDEX `idemergencies_UNIQUE` (`idEmergencyPatients` ASC) VISIBLE,
  INDEX `documentNumber_INDEX` (`documentNumberEmergencyPatients` ASC) VISIBLE,
  INDEX `heightWeightRatio_INDEX` (`heightWeightRatioEmergencyPatients` ASC) VISIBLE,
  INDEX `priority_INDEX` (`priorityEmergencyPatients` ASC) VISIBLE,
  INDEX `risk_INDEX` (`riskEmergencyPatients` ASC) VISIBLE,
  INDEX `priorityRisk_INDEX` (`riskEmergencyPatients` ASC, `priorityEmergencyPatients` ASC) VISIBLE,
  INDEX `weight_INDEX` (`weightEmergencyPatients` ASC) VISIBLE,
  INDEX `height_INDEX` (`heightEmergencyPatients` ASC) VISIBLE,
  INDEX `somker_INDEX` (`smokerEmergencyPatients` ASC) VISIBLE,
  INDEX `status_INDEX` (`statusEmergencyPatients` ASC) VISIBLE,
  FULLTEXT INDEX `status_FULLTEXT` (`statusEmergencyPatients`) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
